apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apache-selector
  template:
    metadata:
      labels:
        run: apache-selector
    spec:
      containers:
      - name: apache-selector
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 20m
          requests:
            cpu: 10m
      nodeSelector:
          disktype: ssd
---
apiVersion: v1
kind: Service
metadata:
  name: apache-selector
  labels:
    run: apache-selector
spec:
  ports:
  - port: 80
  selector:
    run: apache-selector
