apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 20m
          requests:
            cpu: 10m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-taint
spec:
  replicas: 2
  selector:
    matchLabels:
      run: php-apache-taint
  template:
    metadata:
      labels:
        run: php-apache-taint
    spec:
      containers:
      - name: php-apache-taint
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 20m
          requests:
            cpu: 10m
      tolerations:
      - key: "key1"
        operator: "Equal"
        value: "value1"
        effect: "NoExecute"
      
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-taint
  labels:
    run: php-apache-taint
spec:
  ports:
  - port: 80
  selector:
    run: php-apache-taint